### ISSUE TITLE
Refresh page will log you out

### ISSUE THREAD

**Issue by rori4** [heyAuraDev/adex-platform#386]
**Describe the bug**
When you refresh the page this will log you out of the platform

**To Reproduce**
1. Login into platform
2. press F5 or refresh the page
3. You will logout

**Expected behavior**
Keep the session and don't logout user.

**Additional context**
When logged in with multiple accounts sometimes it happens so that when I refresh it goes into another account

**Comment by ivopaunov** [comment]
It does not log you out every time.
It's not so simple to reproduce it.

**Comment by ivopaunov** [comment]
Maybe if you have multiple tabs with different accounts it can happen

**Comment by ivopaunov** [comment]
There are 2 cases when you can log out. If the market return `401` or when you requesting some analytics or items. Because this request takes a lot of time there is a check if the account is the same at the end of the request. If it is different it logs you out. Maybe it should not log out but just not update the data.

**Comment by rori4** [comment]
I think it happens if you log in first with a quick account. And then login with a metamask account.
