### ISSUE TITLE
Edit option for active campaigns

### ISSUE THREAD

**Issue by Vesi5** [heyAuraDev/adex-platform#654]
We need to add an option for users to edit their campaign after they activate it. This will be available on the Dashboard in the action buttons.
![image (2)](https://github.com/user-attachments/assets/c67efc1d-3154-44ce-bdd8-bc8bed8fe07c)

The "Edit" button will open a page similar to that of the "Campaign Details" where they will be able to make changes.

Editable will be: 
- min/max CPM
- categories
- countries
- creatives (at a later stage, but please consider it now in the design, so that we don't have to re-do the page in the future) 

Non-editable are: 
- title
- status
- served %
- budget
- created
- starts
- ends

@MiroslavKr can you please make a design of the edit screen.

**Comment by MiroslavKr** [comment]
**1. Added** "edit" icon in the Action section. In the future we can add more actions under the three-dots-menu

![Image](https://github.com/user-attachments/assets/16e0a6d5-de2a-4831-92a4-1884fb80b154)


**2. Created** - the edit campaign page

![Image](https://github.com/user-attachments/assets/a8657e6c-d6c6-4f45-9334-7a7f3f968574)


**3. Modified** - instead of the big Activate, Pause, Stop, Archive buttons, I replaced them with smaller navigation bar on top of the screen. There I added also the Edit button. That way it looks more sleek, saves space + there is now more room for the Creatives

![Image](https://github.com/user-attachments/assets/3e683250-232d-4bc2-8e83-95aba92482f9)

![Image](https://github.com/user-attachments/assets/99c155de-af43-406e-b222-60845d6ef58e)




**You can test it [here](https://xd.adobe.com/view/3bfe62ce-6673-44fa-ae98-d12e3aa6f8ff-6ead/screen/0847b56d-a9bc-4284-b0f9-786e60f482f9/)**
